### PR TITLE
Rework of the backend-module

### PR DESCRIPTION
**Pull request by OlegSchmidt**
Code :
complete rework of the module
task based classes (handler, connector, errors, validator, api-endpoints etc.)
very detailed logging to pre-validate the complex configuration file
additional connection type implemented (MySQL)
possibility to generate MySQL-Queries for the tables (to reduce the effort), results provided via endpoint
possibility to on-demand-creation of MySQL tables for storing the data
providing configuration for the logging via endpoint

Misc :
update of requirements
specific docker files for linux/windows
complete documentation of the configuration via RAML
JS-files for logging in ES5 (generated) and ES6 (written)

### CODE REVIEW

**Comment by OlegSchmidt** [comment]
I see that i need to update the documentation (.md file).
I will do it tomorrow, but if you have time, feel free to already start looking into the changes.

**Comment by LloydThinks** [comment]
@ChristophStanik , have you looked at this?

**Comment by ChristophStanik** [comment]
@VolodymyrBiryuk is managing is component.

**Comment by LloydThinks** [comment]
@VolodymyrBiryuk Any updates?

**Review by VolodymyrBiryuk — APPROVED** [review]
Approved.

**Pull request merged**
